version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipegpt-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: recipegpt-frontend
  #   restart: always
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=/api

volumes:
  mongodb-data: